### ISSUE TITLE
dynamic setting of instance name

### ISSUE THREAD

**Issue by joemiller** [graphite-ng/carbon-relay-ng#236]
It would be desirable to dynamically populate the `instance` name. Currently it is hardcoded in the ini file eg: `instance = "default"`. Is there an existing mechanism to set this dynamically, such as from an ENV var or by using the hostname?

My particular use case is for deployment in Kubernetes. There may be one or more instances of carbon-relay-ng and they can be scaled up/down relatively easily. I'd like to have metrics from each with minimal effort.

Other parts of the graphite stack support this via hostname or fqdn, for example, `go-carbon`'s config file:
```
graph-prefix = "carbon.go-carbon.{host}"
```

and `carbonapi`'s config file:
```
graphite:
         # Host:port where to send internal metrics
         # Empty = disabled
         host: "go-carbon:2003"
        interval: "60s"
         prefix: "carbon.carbonapi"
         pattern: "{prefix}.{fqdn}"
```

A current solution is to augment the container to run a small script which sed's the hostname into the ini file before starting carbon-relay-ng. This is do-able but a bit awkward and nice to avoid if possible. It would be preferred to set this dynamically at runtime via hostname or env var.
